root: true
extends: ['./packages/eslint-config', 'plugin:prettier/recommended', 'prettier']
plugins: ['prettier']
parserOptions:
  project: tsconfig.json
rules:
  prettier/prettier: error
env:
  node: true
