name: Continuous Integration
on:
  push:
    branches: [main]
    paths-ignore: ['*.{md,txt}', LICENSE, .*config, .vscode]
    tags-ignore: ['*']
  pull_request:
    branches: ['*']
    paths-ignore: ['*.{md,txt}', LICENSE, .*config, .vscode]

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.17.x, 12, 15, 16]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js v${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install --immutable

      - name: Lint
        run: yarn lint
