name: Continuous Integration
on: [push, pull_request]

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.17.x, 12, 15]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js v${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install --immutable

      - name: Lint
        run: yarn lint
